# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "virtio_pci" "ahci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-2c420432-81be-4a28-b6d6-3d281e7136f0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2c420432-81be-4a28-b6d6-3d281e7136f0".device = "/dev/disk/by-uuid/2c420432-81be-4a28-b6d6-3d281e7136f0";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/722B-359C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
